import { Metadata } from 'next'

export const metadata: Metadata = {
  title: {
    absolute: "Blog", // This overrides the default title
  },
  description: 'Generated by Next.js',
}

export default function Blog () {
  return (
    <div>
      <h1>Blog</h1>
    </div>
  );
}